import {
  topProduct,
  topProduct1,
  topProduct2,
  topProduct3,
  topProduct4,
  topProduct5,
  topProduct6,
  topProduct7,
} from "./assets/images";

export const products = [
  {
    id: 1,
    title: "Adicolor Classics Joggers",
    category: "Dress",
    price: 63.85,
    image: topProduct6,
    status: "Best Selers",
  },
  {
    id: 2,
    title: "Nike Sportswear Futura Luxe",
    category: "Bag",
    price: 130.0,
    image: topProduct1,
    status: "Best Selers",
  },
  {
    id: 3,
    title: "Geometric print Scarf",
    category: "Dress",
    price: 53.0,
    image: topProduct4,
    status: "Best Selers",
  },
  {
    id: 4,
    title: "Yellow Reserved Hoodie",
    category: "Hoodies",
    price: 63.85,
    image: topProduct5,
    status: "New Arriaval",
  },
  {
    id: 5,
    title: "Basic Dress Green",
    category: "Dress",
    price: 236.0,
    image: topProduct,
    status: "New Arriaval",
  },
  {
    id: 6,
    title: "Nike Air Zoom Pegasus",
    category: "Shoe",
    price: 198.0,
    image: topProduct2,
    status: "Best Selers",
  },
  {
    id: 7,
    title: "Nike Repel Miler",
    category: "Hoodies",
    price: 120.5,
    image: topProduct3,
    status: "Best Selers",
  },
  {
    id: 8,
    title: "Nike Sportswear Futura Luxe",
    category: "Glasses",
    price: 160.0,
    image: topProduct7,
  },
];
